source 'https://rubygems.org'

gem 'rails', '4.2.5.1'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc

# Admin
gem 'rails_admin'

# Authorization and authentication
gem 'devise'
gem 'bcrypt', '~> 3.1.7'

# Image processing
gem 'carrierwave'
gem 'mini_magick'

# QR code generation
gem 'barby'
gem 'rqrcode'
gem 'cairo'

group :development, :test do
  gem 'sqlite3'
  gem 'byebug'
  gem 'rspec-rails'
end

group :test do
  gem 'shoulda'
  gem 'shoulda-matchers'
end

group :development do
  gem 'web-console', '~> 2.0'
  gem 'spring'
  gem 'capistrano', require: false
  gem 'capistrano-rvm', require: false
  gem 'capistrano-rails', require: false
  gem 'capistrano-bundler', require: false
  gem 'capistrano3-puma', require: false
  gem 'capistrano-secrets-yml', '~> 1.0.0'
end

group :production do
  gem 'puma'
  gem 'mysql2'
end
